<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- <ProjectReference Include="..\..\Jint\Jint\Jint.csproj" /> -->
    <PackageReference Include="Jint" />
    <ProjectReference Include="..\Jither.DebugAdapter\Jither.DebugAdapter.csproj" />
  </ItemGroup>

</Project>
